import Head from "next/head";
import Footer from "../Components/Footer";
import Header from "../Components/Header";

export default function Home() {
  return (
    <>
      <Header />
      <div>
        <Head>
          <title>ICEBURG✔More than Faster</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <h1>ICEBURG-Food Delivery WebApp</h1>
          <h2>Hello Hungry!</h2>
        </main>
      </div>
      <Footer />
    </>
  );
}
