import Head from "next/head";
import css from "../styles/Home.module.css";
import Footer from "../Components/Footer";
import Header from "../Components/Header";
import Hero from "../Components/Hero";
import Services from "../Components/Services";

export default function Home() {
  return (
    <>
      <Header />
      <div className={css.container}>
        <Head>
          <title>ICEBURG✔More than Faster</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services />
        </main>
      </div>
      <Footer />
    </>
  );
}
